name: Node CI

on: [pull_request] # Run on Pull Requests

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.x] # Only run the 10.x build

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: yarn install & build, and test
      run: |
        lerna bootstrap
        lerna run compile
        lerna run ci